{% set name = "anakin-language-server" %}
{% set version = "1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anakin_language_server-{{ version }}.tar.gz
  sha256: a9b92535339df0179a3a74dc7019f636913ac2d266aee3fdd651c0c66aa01b71

build:
  entry_points:
    - anakinls = anakinls.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jedi >=0.19.0
    - pygls >=1.3,<1.4
    - pyflakes >=2.2,<3.dev0
    - pycodestyle >=2.5,<3.dev0
    - yapf >=0.30,<1.dev0

test:
  imports:
    - anakinls
  commands:
    - pip check
    - anakinls --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/muffinmad/anakin-language-server
  summary: Yet another Jedi Python language server
  dev_url: https://github.com/muffinmad/anakin-language-server
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
